### ISSUE TITLE
Cannot fully minify with UglifyJS. Breaks build

### ISSUE THREAD

**Issue by iansinnott** [kryptnostic/kryptnostic-js#157]
This lib doesn't seem to be fully minifyable using UglifyJS version `2.6.1`. This is a significant issue for two reason:

* It will break any build that has a minification step using uglifyjs
* At over 1mb unminified the umd bundle isn't suitable for unminified inclusion in a project

I can reproduce by running uglifyjs directly on the command line like so:

```
uglifyjs --compress --mangle -- node_modules/kryptnostic-js/dist/kryptnostic.umd.js
```

The script has been running for a few minutes now while I write up this issue and there hasn't been any new output since the initial warnings:

```
WARN: Side effects in initialization of unused variable support [node_modules/kryptnostic-js/dist/kryptnostic.umd.js:1185,9]
WARN: Condition always true [node_modules/kryptnostic-js/dist/kryptnostic.umd.js:12576,7]
WARN: Dropping unreachable code [node_modules/kryptnostic-js/dist/kryptnostic.umd.js:12590,8]
WARN: Side effects in initialization of unused variable moduleExports [node_modules/kryptnostic-js/dist/kryptnostic.umd.js:519,7]
WARN: Condition always true [node_modules/kryptnostic-js/dist/kryptnostic.umd.js:12629,100]
WARN: Condition always true [node_modules/kryptnostic-js/dist/kryptnostic.umd.js:12906,190]
WARN: Dropping unused function p [node_modules/kryptnostic-js/dist/kryptnostic.umd.js:12906,173129]
WARN: Side effects in initialization of unused variable o [node_modules/kryptnostic-js/dist/kryptnostic.umd.js:12906,254423]
WARN: Dropping unused variable n [node_modules/kryptnostic-js/dist/kryptnostic.umd.js:12906,225086]
WARN: Dropping unused variable N [node_modules/kryptnostic-js/dist/kryptnostic.umd.js:12906,242497]
```

After some significant debugging it turned out that the `--compress` option is somehow causing uglify to hang and eventually fail after over an hour. Disabling this option in Webpack is doable, but it's certainly not ideal:

```js
new webpack.optimize.UglifyJsPlugin({
  screw_ie8: true,
  compressor: false, // <-- disable compressor
}),
```

The compressor option is enabled by default because it's usually a free optimization that can be applied on top of a codebase. Not being able to use this option is not ideal for a library that's meant to be included in other projects.

This caveat should be added to the README so consumers of the lib are forewarned that simply including the library may break their production build.

**Comment by UnsungHero97** [comment]
hey @iansinnott , thanks for the super detailed post. it seems like the problem is due to our dependency on forge. if you look at `webpack.config.js`, you'll see that we're bundling the minified version of forge. changing `FORGE_PATH` to point to the non-minified file `forge.js` fixes the problem.
