### ISSUE TITLE
Timing attack on HMAC validation when AES-GCM isn't used

### ISSUE THREAD

**Issue by paragonie-scott** [kryptnostic/kryptnostic-js#190]
Relevant line of code: https://github.com/kryptnostic/kryptnostic-js/blob/f25773cd5543518791c4272293ca908fa9016d8a/js/src/crypto/AesCryptoService.coffee#L48

See also: http://blog.ircmaxell.com/2014/11/its-all-about-time.html

**Comment by UnsungHero97** [comment]
thanks for reporting! I'll work on a fix.

**Comment by UnsungHero97** [comment]
@paragonie-scott I have a PR with the fix: https://github.com/kryptnostic/kryptnostic-js/pull/191
